version: "4.0"
services:
    zabbix-proxy-v4:
        image: dockerglobalcare/zbx-prx-6.4.10:1.0
        container_name: proxyzbx6.4
        hostname: proxyzbx6.4.10
        ports:
            - $IP:10051:10051
        #cap_add: ['NET_ADMIN']
        #devices:
            #- /dev/net/tun
        environment:
            - ZBX_HOSTNAME=$ZBX_HOSTNAME
            - ZBX_SERVER_HOST=$ZBX_SERVER_HOST
            - ZBX_DEBUGLEVEL=$ZBX_DEBUGLEVEL
            - ZBX_TIMEOUT=$ZBX_TIMEOUT
            - ZBX_PROXYLOCALBUFFER=$ZBX_PROXYLOCALBUFFER
            - ZBX_PROXYOFFLINEBUFFER=$ZBX_PROXYOFFLINEBUFFER
            - ZBX_CONFIGFREQUENCY=$ZBX_CONFIGFREQUENCY
            - ZBX_STARTPOLLERS=$ZBX_STARTPOLLERS
            - ZBX_STARTPOLLERSUNREACHABLE=$ZBX_STARTPOLLERSUNREACHABLE
            - ZBX_STARTTRAPPERS=$ZBX_STARTTRAPPERS
            - ZBX_STARTPINGERS=$ZBX_STARTPINGERS
            - ZBX_CACHESIZE=$ZBX_CACHESIZE
            - ZBX_HISTORYCACHESIZE=$ZBX_HISTORYCACHESIZE
            - ZBX_HISTORYINDEXCACHESIZE=$ZBX_HISTORYINDEXCACHESIZE
            - ZBX_STARTVMWARECOLLECTORS=$ZBX_STARTVMWARECOLLECTORS
            - ZBX_VMWAREFREQUENCY=$ZBX_VMWAREFREQUENCY
            - ZBX_VMWAREPERFFREQUENCY=$ZBX_VMWAREPERFFREQUENCY
            - ZBX_VMWARECACHESIZE=$ZBX_VMWARECACHESIZE
            - ZBX_VMWARETIMEOUT=$ZBX_VMWARETIMEOUT
            - TNS_ADMIN=/usr/lib/oracle/12.1/client64/network/admin
            - ZBX_TLSCONNECT=psk
            - ZBX_TLSPSKIDENTITY=$ZBX_HOSTNAME
            - ZBX_TLSPSKFILE=tls.psk
            - ZBX_SERVER_PORT=$ZBX_SERVER_PORT
            - ZBX_ENABLEREMOTECOMMANDS=1
            - ZBX_DATASENDERFREQUENCY=$ZBX_DATASENDERFREQUENCY
            - ZBX_STARTPREPROCESSORS=$ZBX_STARTPREPROCESSORS
            - ZBX_IPMIPOLLERS=$ZBX_IPMIPOLLERS
            - ZBX_STARTDISCOVERERS=$ZBX_STARTDISCOVERERS
            - ZBX_STARTHISTORYPOLLERS=$ZBX_STARTHISTORYPOLLERS
            - ZBX_STARTHTTPPOLLERS=$ZBX_STARTHTTPPOLLERS
            - ZBX_STARTODBCPOLLERS=$ZBX_STARTODBCPOLLERS
            - ZBX_JAVAGATEWAY=zabbix-java-gateway
            - ZBX_JAVAGATEWAYPORT=10052
            - ZBX_STARTJAVAPOLLERS=$ZBX_STARTJAVAPOLLERS
            - ZBX_ENABLE_SNMP_TRAPS=$ZBX_ENABLE_SNMP_TRAPS
            - ZBX_LISTENBACKLOG=$ZBX_LISTENBACKLOG
            - ZBX_HOUSEKEEPINGFREQUENCY=$ZBX_HOUSEKEEPINGFREQUENCY
            - ZBX_STARTDBSYNCERS=$ZBX_STARTDBSYNCERS
            - ZBX_TRAPPERTIMEOUT=$ZBX_TRAPPERTIMEOUT
            - ZBX_UNREACHABLEPERIOD=$ZBX_UNREACHABLEPERIOD
            - ZBX_UNAVAILABLEDELAY=$ZBX_UNAVAILABLEDELAY
            - ZBX_UNREACHABLEDELAY=$ZBX_UNREACHABLEDELAY
            - ZBX_LOGSLOWQUERIES=$ZBX_LOGSLOWQUERIES
            
        volumes:
            - /opt/bs4it/zabbix-proxy/scripts/externalscripts:/usr/lib/zabbix/externalscripts
            - /opt/bs4it/zabbix-proxy/scripts/alertscripts:/usr/lib/zabbix/alertscripts
            - /opt/bs4it/zabbix-proxy/tnsnames.ora:/usr/lib/oracle/12.1/client64/network/admin/tnsnames.ora
            - /opt/bs4it/zabbix-proxy/tls.psk/:/var/lib/zabbix/enc/tls.psk
            - /usr/share/snmp/mibs:/usr/share/snmp/mibs
            - /etc/odbc.ini:/etc/odbc.ini
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - /etc/hosts:/etc/hosts
#            - /etc/resolv.conf:/etc/resolv.conf
        restart: always
        networks:
           zbx-network:
              ipv4_address: $IP_CONTAINER
networks:
  zbx-network:
    ipam:
      driver: default
      config:
        - subnet: $IP_SUBNET
