networks:
  zbx-network:
    ipam:
      config:
      - subnet: 172.25.0.0/24
      driver: default
services:
  zabbix-proxy-v4:
    cap_add:
    - NET_ADMIN
    container_name: zabbix-proxy7
    environment:
    - ZBX_PROXYMODE=0  # 0 - active proxy and 1 - passive proxy'
    - ZBX_DEBUGLEVEL=3
    - ZBX_ENABLEREMOTECOMMANDS=1
    - ZBX_PROXYLOCALBUFFER=1
    - ZBX_PROXYOFFLINEBUFFER=1
    - ZBX_PROXYHEARTBEATFREQUENCY=60
    - ZBX_PROXYCONFIGFREQUENCY=200
    - ZBX_DATASENDERFREQUENCY=1
    - ZBX_STARTHISTORYPOLLERS=2
    - ZBX_STARTPOLLERS=15
    - ZBX_STARTPREPROCESSORS=20
    - ZBX_STARTPOLLERSUNREACHABLE=10
    - ZBX_STARTPINGERS=10
    - ZBX_STARTDISCOVERERS=5
    - ZBX_STARTHTTPPOLLERS=5
    - ZBX_HOUSEKEEPINGFREQUENCY=1
    - ZBX_STARTVMWARECOLLECTORS=1
    - ZBX_VMWAREFREQUENCY=60
    - ZBX_VMWAREPERFFREQUENCY=60
    - ZBX_VMWARECACHESIZE=32M
    - ZBX_VMWARETIMEOUT=300
    - ZBX_CACHESIZE=32M
    - ZBX_STARTDBSYNCERS=10
    - ZBX_HISTORYCACHESIZE=32M
    - ZBX_HISTORYINDEXCACHESIZE=32M
    - ZBX_TIMEOUT=30
    - ZBX_UNREACHABLEPERIOD=10
    - ZBX_UNAVAILABLEDELAY=10
    - ZBX_UNREACHABLEDELAY=10
    - ZBX_LOGSLOWQUERIES=3000
    - ZBX_TLSCONNECT=psk
    - ZBX_TLSACCEPT=psk
    - ZBX_TLSPSKFILE=tls.psk
    - ZBX_HOSTNAME=elfamedicamentos.docker.prx.globalcare
    - ZBX_SERVER_HOST=h.bs4it.com.br:10053
    - ZBX_TLSPSKIDENTITY=elfamedicamentos.docker.prx.globalcare
    hostname: proxy
    image: dockerglobalcare/zbx-prx-7.0.2:v4
    networks:
      zbx-network:
        ipv4_address: 172.25.0.100
    ports:
    - 10051:10051
    restart: always
    volumes:
    - /opt/bs4it/zabbix-proxy/scripts/:/usr/lib/zabbix/externalscripts
    - /opt/bs4it/zabbix-proxy/tls.psk:/var/lib/zabbix/enc/tls.psk
    - /opt/bs4it/zabbix-proxy/mib/:/usr/share/snmp/mibs/
    - /etc/odbc.ini:/etc/odbc.ini
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    - /etc/hosts:/etc/hosts
version: '4.0'
